# Generated by Django 5.2.11 on 2026-02-27 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GoldPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gold_type",
                    models.CharField(
                        choices=[
                            ("gram", "Gram Altın"),
                            ("ceyrek", "Çeyrek Altın"),
                            ("yarim", "Yarım Altın"),
                            ("tam", "Cumhuriyet (Tam) Altın"),
                            ("gumus", "Gümüş (Gram)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("price_buy", models.DecimalField(decimal_places=2, max_digits=10)),
                ("price_sell", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
